// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhTbgjlCsYiw7A7dEpasHHMwDIuQjj_E8',
    appId: '1:856997205148:web:6663c6291be9492705c959',
    messagingSenderId: '856997205148',
    projectId: 'rick-and-morty-wikiapp2-jlcf',
    authDomain: 'rick-and-morty-wikiapp2-jlcf.firebaseapp.com',
    storageBucket: 'rick-and-morty-wikiapp2-jlcf.firebasestorage.app',
    measurementId: 'G-WSTQ5W2N6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmPTz-lAOlIX9-w7yMJEmBvnqrcH53W7I',
    appId: '1:856997205148:android:8eb205db35ef8ca305c959',
    messagingSenderId: '856997205148',
    projectId: 'rick-and-morty-wikiapp2-jlcf',
    storageBucket: 'rick-and-morty-wikiapp2-jlcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzPoXwpc1tE48qRhZFa2hlx5YtgAmL-9Q',
    appId: '1:856997205148:ios:f082178a131eca5505c959',
    messagingSenderId: '856997205148',
    projectId: 'rick-and-morty-wikiapp2-jlcf',
    storageBucket: 'rick-and-morty-wikiapp2-jlcf.firebasestorage.app',
    iosBundleId: 'com.example.actividad36',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzPoXwpc1tE48qRhZFa2hlx5YtgAmL-9Q',
    appId: '1:856997205148:ios:f082178a131eca5505c959',
    messagingSenderId: '856997205148',
    projectId: 'rick-and-morty-wikiapp2-jlcf',
    storageBucket: 'rick-and-morty-wikiapp2-jlcf.firebasestorage.app',
    iosBundleId: 'com.example.actividad36',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhTbgjlCsYiw7A7dEpasHHMwDIuQjj_E8',
    appId: '1:856997205148:web:57ee2da1a5baad3605c959',
    messagingSenderId: '856997205148',
    projectId: 'rick-and-morty-wikiapp2-jlcf',
    authDomain: 'rick-and-morty-wikiapp2-jlcf.firebaseapp.com',
    storageBucket: 'rick-and-morty-wikiapp2-jlcf.firebasestorage.app',
    measurementId: 'G-203DED7F2M',
  );
}
